### ISSUE TITLE
Can't see balance / vote

### ISSUE THREAD

**Issue by xkikeg** [xharaken/john-law-coin#4]
1. Stuck  on page load with `loading...`.

```
inpage.js:1 MetaMask - RPC Error: Internal JSON-RPC error. {code: -32603, message: 'Internal JSON-RPC error.', data: {…}}code: -32603data: {code: -32000, message: 'header not found'}message: "Internal JSON-RPC error."[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
(anonymous) @ inpage.js:1
(anonymous) @ inpage.js:17
_runReturnHandlers @ inpage.js:17
_processRequest @ inpage.js:17
await in _processRequest (async)
_handle @ inpage.js:17
handle @ inpage.js:17
_rpcRequest @ inpage.js:1
(anonymous) @ inpage.js:1
request @ inpage.js:1
bound bound request @ web3.min.js:13
c.send @ web3.min.js:13
h @ web3.min.js:8
n @ web3.min.js:8
d._executeMethod @ web3.min.js:13
showOracleStatus @ wallet.js:909
await in showOracleStatus (async)
showAdvancedInfo @ wallet.js:885
window.onload @ wallet.js:175
load (async)
(anonymous) @ wallet.js:21
web3.min.js:8 Uncaught (in promise) Error: Internal JSON-RPC error.
{
  "code": -32000,
  "message": "header not found"
}
    at Object._fireError (web3.min.js:8:95770)
    at o (web3.min.js:8:119011)
    at a (web3.min.js:13:9087)
    at U (web3.min.js:13:8017)
    at b.run (web3.min.js:8:83782)
    at p (web3.min.js:8:83276)
```

2. Vote failed (hard to reproduce as I can't even see the balance)

システムエラーでvoteできないときは詫びコインですか? (just kidding) ;-)

**Comment by xkikeg** [comment]
I could have voted once I switched to main net, back to Polygon.

**Comment by xharaken** [comment]
Thanks for reporting! I experienced the same issue and it looks like this is a stability issue of Metamask & Infura (out of control of JohnLawCoin).

**Comment by xkikeg** [comment]
Now I find this error is recurring.
